name: testsdk
description: "Your app description here"
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0  # Updated from ^2.32.0
  firebase_auth: ^5.5.2  # Updated from ^4.20.0
  firebase_storage: ^12.4.5  # Updated from ^11.7.7
  cloud_firestore: ^5.6.6  # Updated from ^4.17.5
  image_picker: ^1.1.2
  video_player: ^2.9.5  # Updated from ^2.9.1
  http: ^1.3.0  # Updated from ^1.2.1
  charts_flutter: ^0.12.0  # Consider removing if not used
  fl_chart: ^0.70.2  # Updated from ^0.65.0
  dio: ^5.8.0+1  # Updated from ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "images/app_logo2.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/players/edwards/
    - images/players/lebron/

  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic