// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5UsSn0DBAdw1t5CdjmMzgmz3fOuHaJ4',
    appId: '1:17493959347:web:f52a8ebc448f4ab11346c6',
    messagingSenderId: '17493959347',
    projectId: 'hooper-proj',
    authDomain: 'hooper-proj.firebaseapp.com',
    storageBucket: 'hooper-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrc0e3rjOY7P82CrJ_6CBpuxKGycKsUys',
    appId: '1:17493959347:android:ef4bcaa6929806751346c6',
    messagingSenderId: '17493959347',
    projectId: 'hooper-proj',
    storageBucket: 'hooper-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaKRcuX53wHP7X1qgbhP-8M15XUvnZdCY',
    appId: '1:17493959347:ios:446d3542a8a8b7c81346c6',
    messagingSenderId: '17493959347',
    projectId: 'hooper-proj',
    storageBucket: 'hooper-proj.appspot.com',
    iosBundleId: 'com.zack.balltrackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaKRcuX53wHP7X1qgbhP-8M15XUvnZdCY',
    appId: '1:17493959347:ios:446d3542a8a8b7c81346c6',
    messagingSenderId: '17493959347',
    projectId: 'hooper-proj',
    storageBucket: 'hooper-proj.appspot.com',
    iosBundleId: 'com.zack.balltrackapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc5UsSn0DBAdw1t5CdjmMzgmz3fOuHaJ4',
    appId: '1:17493959347:web:3507dd720983e3811346c6',
    messagingSenderId: '17493959347',
    projectId: 'hooper-proj',
    authDomain: 'hooper-proj.firebaseapp.com',
    storageBucket: 'hooper-proj.appspot.com',
  );
}
